global:
  scrape_interval: 1s
  #  evaluation_interval: 15s external_labels:
  #    monitor: 'swarm' Load and evaluate rules in this file every evaluation_interval seconds rule_files: - "alert.rules"

scrape_configs:
  - job_name: 'prometheus'
    static_configs:
      - targets: ['localhost:9090']
  - job_name: 'node-exporter'
    dns_sd_configs:
      - names: ['tasks.node-exporter']
        type: 'A'
        port: 9100
  - job_name: 'cadvisor'
    dns_sd_configs:
      - names: ['tasks.cadvisor']
        type: 'A'
        port: 8080      
  - job_name: 'cassandra-seed'
    dns_sd_configs:
      - names: ['tasks.cassandra-seed']
        type: 'A'
        port: 31500
  - job_name: 'cassandra-node'
    dns_sd_configs:
      - names: ['tasks.cassandra-node']
        type: 'A'
        port: 31500
