version: "3"

services:

  prometheus:
    build: prom
    image: seb/prometheus
    command:
      - '-config.file=/etc/prometheus/prometheus.yml'
      - '-storage.local.path=/prometheus'
    ports:
      - "9090:9090"
    networks:
      - monitoring
      - cassandra_net
    deploy:
      replicas: 1
      placement:
        constraints: [node.role == manager]
      restart_policy:
        condition: on-failure


  node-exporter:
    image: prom/node-exporter
    command: -collector.procfs /host/proc -collector.sysfs /host/sys -collector.filesystem.ignored-mount-points "^/(sys|proc|dev|host|etc)($$|/)"
    volumes:
      - "/proc:/host/proc"
      - "/sys:/host/sys"
      - "/:/rootfs"
    networks:
      - monitoring
    deploy:
      mode: global
      restart_policy:
        condition: on-failure      


  cadvisor:
    image: google/cadvisor
    volumes:
      - "/:/rootfs"
      - "/var/run:/var/run"
      - "/sys:/sys"
      - "/var/lib/docker:/var/lib/docker:ro"
    networks:
      - monitoring
    deploy:
      mode: global
      restart_policy:
        condition: on-failure

  grafana:
    image: grafana/grafana
    ports:
      - "3000:3000"
    volumes:
      - "/var/lib/grafana:/var/lib/grafana"
    environment:
      GF_SECURITY_ADMIN_PASSWORD: "${PASSWORD}"
      GF_USERS_ALLOW_SIGN_UP: "false"
    depends_on:
      - prometheus
    networks:
      - monitoring
    deploy:
      replicas: 1
      restart_policy:
        condition: on-failure

networks:
  monitoring:
    driver: overlay

